DAYS = 5
PERIODS_PER_DAY = 5
ALL_SLOTS = set((weekday, timeslot) for weekday in range(DAYS) for timeslot in range(PERIODS_PER_DAY))

HARD_WEIGHT = 0.7
SOFT_WEIGHT = 0.3

HARD_PENALTY = 1
MIN_WORKING_DAYS_PENALTY = 5
CURRICULUM_COMPACTNESS_PENALTY = 2
ROOM_STABILITY_PENALTY = 1
ROOM_CAPACITY_PENALTY = 1
