#HARD_WEIGHT = 0.7
#SOFT_WEIGHT = 0.3

DEFAULT_TIME_LIMIT = 300

HARD_PENALTY = 1
MIN_WORKING_DAYS_PENALTY = 5
CURRICULUM_COMPACTNESS_PENALTY = 2

HC_IDLE = 5000

PRUNING = True
HILL_CLIMBING = True
DIVING = True
DEBUG_RANDOM_SIMULATION = False

MAX_RETRIES = 3
WAIT_TIME = 10
DEBUG_EXCEL = True
DEBUG_TREE = False
DEBUG_PROGRESS = False
DEBUG_LOG = True
DEBUG_PROFILER = True
#DEBUG_PRINT = False
